language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Sx0fuSnp41BTxPp6O9SjNJP7RZ37gzdCDVLY7aELar/0pgDWCNNnVRPjnMQahz81OTXUDNqpS+/udgW/AP8rrGENbbK0dxEGNnuP74+aDQDEVc7GQeHmDZaVMMs8cjm+o1+ZFxpWRh5R+LNTMPRpD1iiqHhmN2XZXEtSsm/TFHsqc5j/uwnyezE66L6dt3nQZUmHmQEm2XriZPhyiKaeWFFl4GGokaeOc9Eb+JdQBupXJwzQmj4a3BkD0XR0PldhBg7dixqLMs2Oe2K1/nMDW7NPkt/7zU2UIMkdbUdAfXokAtinRS2DYUrzwFHma8u8X03fO2hC4u9afiv/7kI7sNInZN3jUOKed1vjjr07rT95JchM5ofRZX2cNkMrlaVpTD5CwNEMcTnbnAgI/2qFY+EdFn5dnQdgFHW8ZaM/jDfI/RL64GJy9hdN9Pa0uEcDA7I7wUQdlz41QcF15ZKglF2zGsGkc5dQaMTmcJhEJJrlNOr9KDtaLsB0XcB02RbiVgJ2BsWkoMCHS7x95Qaw813SVex6A25ZdPgqCSBriymECQjHJpB1duu5mykB6JdWyiX+kNB6rq9k4z9TnrDnY5IPl6tHEk6hHYwa5uRqTpOW3CRQCRzSOp3Sze/YII7FUjpeed1DfcrgYLieTliAK25AiQBgrT9ZzDiql6ubMsM=
