ALTER TABLE TEAM ADD COLUMN created_at TIMESTAMP;
ALTER TABLE TEAM ADD COLUMN payment_transaction_id VARCHAR(255);
ALTER TABLE TEAM ADD COLUMN payment_status VARCHAR(255);
ALTER TABLE TEAM ADD COLUMN payment_processed_at TIMESTAMP(255);
