ALTER TABLE TEAM
  ADD COLUMN created_at TIMESTAMP;
ALTER TABLE TEAM
  ADD COLUMN payment_transaction_id VARCHAR(255);
ALTER TABLE TEAM
  ADD COLUMN payment_status VARCHAR(255);
ALTER TABLE TEAM
  ADD COLUMN payment_processed_at TIMESTAMP(255);
ALTER TABLE TEAM
  ADD COLUMN payment_verification_code INTEGER;


CREATE TABLE PAYPAL_MESSAGE
(
  id              BIGSERIAL PRIMARY KEY,
  transaction_id  VARCHAR(255),
  subscription_id VARCHAR(255),
  payment_status  VARCHAR(255),
  payer_email     VARCHAR(255),
  timestamp       TIMESTAMP
);
CREATE UNIQUE INDEX PAYPAL_MESSAGE_ID_UINDEX
  ON PAYPAL_MESSAGE (id);
