ALTER TABLE TOURNAMENT
  ADD COLUMN paypal_button_id VARCHAR(20);

UPDATE TOURNAMENT SET paypal_button_id = '6TL5WH2R937TL' WHERE id = 1;
UPDATE TOURNAMENT SET paypal_button_id = 'LQPD6XMHDSFHE' WHERE id = 2;
