ALTER TABLE TEAM RENAME COLUMN level TO level_old;
ALTER TABLE TEAM ADD COLUMN level VARCHAR(20);
UPDATE TEAM SET level = 'NATIONAL' WHERE level_old = 1;
UPDATE TEAM SET level = 'REGIONAL' WHERE level_old = 2;
UPDATE TEAM SET level = 'DEPARTEMENTAL' WHERE level_old = 3;
UPDATE TEAM SET level = 'LOISIRS' WHERE level_old = 4;
ALTER TABLE TEAM DROP COLUMN level_old;