CREATE TABLE FEATURE
(
  id      BIGSERIAL PRIMARY KEY,
  name    VARCHAR(255) NOT NULL,
  enabled BOOLEAN DEFAULT FALSE
);
CREATE UNIQUE INDEX FEATURE_ID_UINDEX
  ON FEATURE (id);

INSERT INTO FEATURE (name, enabled) VALUES ('checkin', FALSE);