ALTER TABLE ROUND
  ADD COLUMN type VARCHAR(20);

CREATE TABLE POOL
(
  id        BIGSERIAL PRIMARY KEY,
  round_id  BIGINT REFERENCES ROUND,
  position  INT,
  team_1_id BIGINT REFERENCES TEAM,
  team_2_id BIGINT REFERENCES TEAM,
  team_3_id BIGINT REFERENCES TEAM
);
CREATE UNIQUE INDEX POOL_ID_UINDEX
  ON POOL (id);
